name: CI

on:
  push:
    branches: [main]
  pull_request:

# 👉 Secrets stehen zentral bereit und gelten für alle Steps
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
  BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd='pg_isready -U postgres'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate SQL migrations (Drizzle)
        run: pnpm db:gen

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build